# Generated by Django 5.1.1 on 2025-02-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='service_icons/')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
