# Generated by Django 5.1.1 on 2025-02-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='email',
        ),
    ]
