# Generated by Django 5.1.1 on 2025-02-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
    ]
