# Generated by Django 5.1.1 on 2025-02-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_booking_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
    ]
