# Generated by Django 5.1.1 on 2025-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_booking_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reciept',
            field=models.ImageField(blank=True, null=True, upload_to='service_icons/'),
        ),
    ]
