# Generated by Django 5.1.1 on 2025-02-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_booking_reciept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
