# Generated by Django 5.1.1 on 2025-03-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_booking_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Booking_date',
            new_name='service_date',
        ),
    ]
