# Generated by Django 5.1.1 on 2025-03-10 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_booking_address_booking_city_booking_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
