# Generated by Django 5.1 on 2025-03-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
