# Generated by Django 5.1 on 2025-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='worker_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='worker_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
