# Generated by Django 5.1 on 2025-03-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_booking_worker_contact_booking_worker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash Payment'), ('Online', 'Online Payment')], default='Cash', max_length=20),
        ),
    ]
