# Generated by Django 5.1 on 2025-04-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
